on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - Cargo.toml
      - Cargo.lock
      - lapce-**
      - .github/workflows/ci.yml
  workflow_dispatch:

name: CI

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

permissions: {}

jobs:
  build:
    name: Rust on ${{ matrix.os }}
    if: github.event.pull_request.draft == false
    needs: [fmt, clippy]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Install dependencies on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo make ubuntu-deps

      - name: Update toolchain
        run: |
          rustup update --no-self-update

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6

      - name: Fetch dependencies
        run: cargo fetch --locked

      - name: Build
        run: cargo build --profile ci --frozen

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: lapce-${{ matrix.os }}
          path: |
            target/ci/lapce*
          retention-days: 1

      - name: Build as portable
        if: startsWith(matrix.os, 'windows')
        run: cargo build --profile ci --frozen --features lapce-app/portable

      - name: Free space on Windows
        if: startsWith(matrix.os, 'windows')
        run: cargo clean

      - name: Run doc tests
        run: cargo test --profile ci --doc --workspace

  fmt:
    name: Formatting and spellchecking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Update toolchain & add rustfmt
        run: |
          rustup update
          rustup component add rustfmt

      - name: Run rustfmt
        run: cargo fmt --all --check

      - name: Spell Check Repo
        uses: crate-ci/typos@00f422f3b19c57bc6338715ebfe3316d38768461

  clippy:
    name: Clippy on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Update toolchain & add clippy
        run: |
          rustup update --no-self-update
          rustup component add clippy

      - name: Install dependencies on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo make ubuntu-deps

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6

      - name: Fetch dependencies
        run: cargo fetch --locked

      - name: Run clippy
        run: cargo clippy --profile ci
